title: Harish Srinivasan # your name (or website title) here
logo: "/images/pp.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I am Harish, and I practice data science and software development.
  <br><br>
  I am curious about Data Science and Software Dev. with 2+ years of experience.
  <br><br>
  <a href="https://www.linkedin.com/in/s-harish/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-169265669-1
